// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Agents():Promise<Array<main.AgentDTO>>;

export function Events():Promise<Array<main.EventDTO>>;

export function Header():Promise<main.HeaderDTO>;
