// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Agents() {
  return window['go']['main']['App']['Agents']();
}

export function Events() {
  return window['go']['main']['App']['Events']();
}

export function Header() {
  return window['go']['main']['App']['Header']();
}
